site_name: 帮助文档 - MoeQing Network - AS200105

theme: 
  name: material
  language: zh
  highlightjs: true

extra_css:
  - css/hidefooter.css

#repo_url: https://github.com/MoeQing-Network/MoeIX-Homepage

nav:
  - Home: index.md
  - Community: community.md
  - Location: location.md
  - Transit: transit.md
  # - Looking Glass: lg.md